-- +goose Up
CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kcal_per_100 INT NOT NULL,
    protein_per_100 INT NOT NULL,
    carbs_per_100 INT NOT NULL,
    fat_per_100 INT NOT NULL,
    nutrition_basis TEXT NOT NULL CHECK  (nutrition_basis IN ('g', 'ml')),
    pieces_allowed BOOLEAN NOT NULL,
    weight_per_unit INT CHECK (
        (pieces_allowed = true AND weight_per_unit IS NOT NULL)
            OR
        (pieces_allowed = false AND weight_per_unit IS NULL)
    ),
    tags TEXT[],
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE recipe_ingredients (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id),
    amount DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL CHECK ( unit IN ('pieces', 'g', 'ml')),
    PRIMARY KEY (recipe_id, ingredient_id)
);

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION validate_recipe_ingredient_unit()
RETURNS TRIGGER AS $$
DECLARE i RECORD;
BEGIN
        SELECT * INTO i FROM ingredients WHERE id = NEW.ingredient_id;
        IF NEW.unit = 'pieces' AND NOT i.pieces_allowed THEN
            RAISE EXCEPTION 'Unit "pieces" not allowed for ingredient %', i.name;
        ELSIF NEW.unit = 'g' AND i.nutrition_basis != 'g' THEN
            RAISE EXCEPTION 'Unit "g" not allowed for ingredient %', i.name;
        ELSIF NEW.unit = 'ml' AND i.nutrition_basis != 'ml' THEN
            RAISE EXCEPTION 'Unit "ml" not allowed for ingredient %', i.name;
        END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER recipe_ingredient_unit_check BEFORE INSERT OR UPDATE ON recipe_ingredients
    FOR EACH ROW EXECUTE FUNCTION validate_recipe_ingredient_unit();
-- +goose StatementEnd

-- +goose Down
DROP TABLE IF EXISTS ingredient;