-- +goose Up

-- Drop old global settings
DROP TABLE IF EXISTS settings;

-- Persons
CREATE TABLE persons (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    gender     TEXT    NOT NULL CHECK (gender IN ('male', 'female', 'other')),
    age        INT     NOT NULL CHECK (age > 0),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Per-person nutritional goals (1:1 with persons, created in same transaction)
CREATE TABLE person_settings (
    person_id      BIGINT PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    target_kcal    INT NOT NULL DEFAULT 2000,
    target_protein INT NOT NULL DEFAULT 150,
    target_carbs   INT NOT NULL DEFAULT 200,
    target_fat     INT NOT NULL DEFAULT 65
);

-- Persisted meal plan entries (person × day × recipe)
CREATE TABLE meal_plan_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id     BIGINT           NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    day_index     INT              NOT NULL CHECK (day_index >= 1),
    recipe_id     BIGINT           NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    serving_grams DOUBLE PRECISION NOT NULL CHECK (serving_grams > 0),
    created_at    TIMESTAMP        NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS meal_plan_entries;
DROP TABLE IF EXISTS person_settings;
DROP TABLE IF EXISTS persons;

CREATE TABLE settings (
    id             INT PRIMARY KEY DEFAULT 1,
    target_kcal    INT NOT NULL DEFAULT 2000,
    target_protein INT NOT NULL DEFAULT 150,
    target_carbs   INT NOT NULL DEFAULT 200,
    target_fat     INT NOT NULL DEFAULT 65
);
INSERT INTO settings DEFAULT VALUES;
