/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as MealPlannerIndexRouteImport } from './routes/meal-planner/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlannerIndexRoute = MealPlannerIndexRouteImport.update({
  id: '/meal-planner/',
  path: '/meal-planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/meal-planner/': typeof MealPlannerIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/meal-planner': typeof MealPlannerIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/meal-planner/': typeof MealPlannerIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/$id'
    | '/ingredients/'
    | '/meal-planner/'
    | '/recipes/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes/$id'
    | '/ingredients'
    | '/meal-planner'
    | '/recipes'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/recipes/$id'
    | '/ingredients/'
    | '/meal-planner/'
    | '/recipes/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIdRoute: typeof RecipesIdRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  MealPlannerIndexRoute: typeof MealPlannerIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planner/': {
      id: '/meal-planner/'
      path: '/meal-planner'
      fullPath: '/meal-planner/'
      preLoaderRoute: typeof MealPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIdRoute: RecipesIdRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  MealPlannerIndexRoute: MealPlannerIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
